---
title: "Microbiome 16S Normal Scalp Metadata Summary"
output: html_document
date: "2025-10-22"
---

```{r setup, message=FALSE, warning=FALSE}
library(dplyr)
library(readr)
library(stringr)

# Load Metadata
meta <- read_csv("metadata/scalp_16s_o.csv")

filtered <- meta %>%
  filter(Seq == "16S",
         Site == "Scalp",
         Dx == "CTRL",
         Time_points == "t=1 (Day 0)"
         )

n_bioproject <- filtered %>% distinct(BioProject) %>% nrow()
cat("Number of BioProjects :", n_bioproject, "\n")
cat("Number of samples :", nrow(filtered), "\n")

filtered <- filtered %>%
  mutate(Subject_core = str_replace(Subject_id, "_.*$", ""))

subject_summary <- filtered %>%
  group_by(BioProject) %>%
  summarise(
    Subject_ids = list(unique(Subject_core)),
    n_unique_subjects = n_distinct(Subject_core),
    .groups = "drop"
  )

cat("Number of subjects:", sum(subject_summary$n_unique_subjects), "\n")

# BioProject-wise Metadata Summary
bioproject_summary <- filtered %>%
  group_by(BioProject) %>%
  summarise(
    Meta_sex  = if_else(any(Sex != "NS" & !is.na(Sex)), "Yes", "No"),
    Meta_age  = if_else(any(Age != "NS" & !is.na(Age)), "Yes", "No"),
    Meta_race = if_else(any(Ethnicity != "NS" & !is.na(Ethnicity)), "Yes", "No"),
    Sample_no  = n(),
    Subject_no = n_distinct(Subject_core),
    Layout      = paste(unique(Layout), collapse = ", "),
    Type = paste(sort(unique(Sample)), collapse = ", "),
    File_no = n() * if_else(any(Layout == "PAIRED"), 2, 1),  # ← 여기 수정
    .groups = "drop"
  ) %>%
  ungroup()

cat("Number of sequence files :", sum(bioproject_summary$File_no), "\n\n")

options(width = 2000)
print(bioproject_summary)
